server:
  port: 8025
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/seata_user?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: root
    password: 148521
    type: com.zaxxer.hikari.HikariDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  application:
    name: user-nacos
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      application: seata-server
      username: nacos
      password: nacos
  tx-service-group: henan
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
logging:
  level:
    io:
      seata: info
