server:
  port: 8024
#nacos配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/seata_user?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 148521
    type: com.zaxxer.hikari.HikariDataSource

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  #服务名
  application:
    name: user-nacos
feign:
  sentinel:
    enabled: true