server:
  port: 8027
spring:
  application:
    name: user-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-nacos #路由的唯一标识，路由到user
          uri: lb://user-nacos #需要转发的地址 lb:使用nacos本地负载均衡策略
          #断言规则 用于路由规则的匹配
          predicates:
            - Path=/user-nacos/**
          filters:
            #内置过滤器，转发之前去掉一级路径
            - StripPrefix=1

        - id: student-nacos #路由的唯一标识，路由到user
          uri: lb://student-nacos #需要转发的地址
            #断言规则 用于路由规则的匹配
          predicates:
            - Path=/student-nacos/**
          filters:
              #内置过滤器，转发之前去掉一级路径
            - StripPrefix=1